version: "3.8"

services:
  proxy:
    image: yano3/nginx-ngx_mruby:latest
    volumes:
      - ./proxy/proxy.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/mruby/:/etc/nginx/mruby/
    ports:
      - "8080:80"
  app:
    build: ./app
    volumes:
      - ./app:/app
